### ISSUE TITLE
config default and argument

### ISSUE THREAD

**Issue by mdaadoun** [Pixailz/Born2BeRootTester#3]
By default 
MONITORING_PATH=
could have
..
This way you could just git clone to your home and start grademe.sh directly
may be an argument
grademe.sh username
to fullfill
LOGIN=
https://linuxhandbook.com/bash-arguments/

**Comment by Pixailz** [comment]
i leave by default blank because people often start with setting up the server and then make the script
i keep the fact of using command arg :)

**Comment by Pixailz** [comment]
added
